version: 0.2
env:
  variables:

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --no-cache-dir -r requirements.txt

  build:
    commands:
      - python console.py --install
      - python console.py --synth
      - aws cloudformation package --template-file projectTemplate.json  --s3-bucket $BUCKETTEMPLATES  --output-template-file projectTemplate.json --use-json


artifacts:
  type: zip
  files:
    - './projectTemplate.json'

